# Generated by Django 4.2 on 2026-05-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofstudy',
            name='num_semesters',
            field=models.IntegerField(default=3),
        ),
    ]
